# Generated by Django 4.0.5 on 2022-06-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprofile',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical profile', 'verbose_name_plural': 'historical profiles'},
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
