# Generated by Django 3.2.9 on 2022-04-27 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=31)),
                ('content', models.TextField()),
                ('likes_value', models.IntegerField()),
                ('pub_date', models.DateTimeField()),
                ('author_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('likes_value', models.IntegerField()),
                ('pub_date', models.DateTimeField()),
                ('author_name', models.CharField(max_length=150)),
                ('question_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home_page_app.questions')),
            ],
        ),
    ]
