# Generated by Django 4.0.4 on 2022-04-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_app', '0003_alter_comments_pub_date_alter_questions_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='content',
            field=models.TextField(unique=True),
        ),
    ]
