# Generated by Django 3.2.9 on 2022-04-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_app', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
