# Generated by Django 4.0.4 on 2022-05-03 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_app', '0004_alter_questions_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page_app.questions'),
        ),
    ]
