# Generated by Django 4.0.4 on 2022-05-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_app', '0005_alter_comments_question_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='question_id',
            new_name='question',
        ),
    ]
