# Generated by Django 4.0.4 on 2022-05-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_app', '0007_alter_comments_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
