# Generated by Django 4.0.4 on 2022-05-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_app', '0008_alter_questions_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('content_type', models.CharField(max_length=30)),
                ('content_id', models.BigIntegerField()),
            ],
        ),
    ]
