# Generated by Django 4.0.4 on 2022-05-15 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home_page_app', '0009_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='likes_value',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='likes_value',
        ),
        migrations.AddField(
            model_name='comments',
            name='likes',
            field=models.ManyToManyField(related_name='comments_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='likes',
            field=models.ManyToManyField(related_name='questions_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questions',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
